'use client'

import { useMemo, useState } from 'react'
import { ArrowUpRight, Camera, Cat, Clock3, Heart, MapPin, PawPrint, ShieldPlus, Sparkles, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

const discordUrl = 'https://discord.gg/u3mV7mMDXP'
const discordIcon = 'https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/discord/default.svg'

const traits = [
  ['全部', '查看店內所有貓咪，讓緣分自己決定。', 'bg-[#c9b8d5]'],
  ['撒嬌', '喜歡窩在你身邊，摸久了會發出呼嚕聲，是最容易黏上你的類型。', 'bg-[#d8a8b7]'],
  ['高冷', '不太主動，但願意讓你靜靜坐在旁邊，是需要耐心的類型。', 'bg-[#9caeb8]'],
  ['調皮', '偶爾會抓一下、咬一下純屬玩鬧，互動最有隨機感的類型。', 'bg-[#a9c3a0]'],
  ['貪吃', '看到小魚乾就衝過來，是最容易被食物吸引的類型。', 'bg-[#cdb389]'],
  ['療癒', '擁有治療傷口的能力，是在醫護站內的小天使貓咪。', 'bg-[#9fc4bb]'],
  ['慵懶', '大部分時間都在打瞌睡，偶爾抬頭看你一眼又睡著了。', 'bg-[#b8a9c6]'],
  ['好奇', '對任何新奇的東西都充滿興趣，可能會一直盯著你的隨身物品。', 'bg-[#9ebbc6]'],
  ['傲嬌', '嘴上嫌你煩，尾巴卻誠實地繞著你的手，偶爾會輕咬一口。', 'bg-[#c99fb8]'],
  ['健談', '很愛用叫聲跟你聊天，彷彿在回應你說的每一句話。', 'bg-[#c5a69a]'],
]
const cats = [
  { name: '札伊', role: '攝影獅', traits: ['好奇', '撒嬌', '健談', '調皮'], intro: '曾是沙漠神官，如今最愛拍照與收集有趣的故事。', detail: '是古老的沙漠神官，因為與某個貓魅族相遇後，獲得了新的軀體得以活在現世。\n\n為了某個約定，所以對新事物很感興趣，也喜歡拍照留念。', likes: '拍照、新奇的事物、故事', quote: '嗯？你好奇我的故事嗎？那...你也將你的故事說給我聽吧～或者讓我拍張照！' },
  { name: '露露', role: '店喵', traits: ['撒嬌', '療癒'], intro: '總是在窗邊迎接客人的溫柔小太陽。' }, { name: '墨爾', role: '喵衛', traits: ['高冷', '慵懶'], intro: '看似冷淡，其實會默默守在你身邊。' }, { name: '可可', role: '接待喵', traits: ['貪吃', '健談'], intro: '記得每位客人的喜好，也記得小魚乾放在哪裡。' }, { name: '斑斑', role: '店喵', traits: ['調皮', '好奇'], intro: '任何會動的東西，都逃不過牠的爪爪。' }, { name: '夜羽', role: '貓店長', traits: ['高冷', '傲嬌'], intro: '店裡真正的話事者，尾巴比嘴巴誠實。' }, { name: '奶糖', role: '店喵', traits: ['撒嬌', '慵懶'], intro: '以最舒服的姿勢，佔據每一張空椅子。' }, { name: '咕咕', role: '喵衛', traits: ['療癒', '健談'], intro: '輕聲喵叫，就能讓緊張的心情慢慢放鬆。' }, { name: '栗子', role: '店喵', traits: ['貪吃', '調皮'], intro: '為了一口點心，願意表演任何新花樣。' }, { name: '星塵', role: '攝影獅', traits: ['好奇', '高冷'], intro: '喜歡躲在遠處觀察，再捕捉最好的瞬間。' }, { name: '小滿', role: '接待喵', traits: ['健談', '撒嬌'], intro: '話題永遠不會中斷的熱情接待員。' }, { name: '灰灰', role: '店喵', traits: ['慵懶', '傲嬌'], intro: '如果牠願意對你眨眼，那就是今日特別優待。' },
]
const zones = [['櫃台', '想購買項目或周邊，到櫃檯找接待喵就對了！', '', PawPrint], ['玩樂區', '', '互動感強烈，撲、抓、追逐都可能發生，這裡玩得比較野，踏進來前先做好心理準備喔。', Sparkles], ['喝茶區', '', '安靜喝茶、聊天，這裡的貓咪性格溫和，只想蹭蹭你、討摸摸。', Heart], ['醫護站', '', '手上有被抓咬的痕跡嗎？來這裡讓貓咪小護士幫你包紮一下。', ShieldPlus]]
const menuGroups = [
  { title: '入場費', items: [['入場費', '50,000 Gil', '含當日套餐一份，於店外向喵衛支付。']] },
  { title: '貓咪互動服務', items: [['小魚乾', '30,000 Gil', '投餵給貓咪也許能增進感情，但請勿將店內貓咪餵成卡車。'], ['貓咪交響樂', '100,000 Gil', '貓咪會在你身旁大聲嚎叫，音量與時長依貓咪心情而定。'], ['特殊服務', '300,000 Gil', '每隻貓咪內容不同，為隨機驚喜服務。']] },
  { title: '醫護站服務', items: [['傷口包紮', '100,000 Gil', '被貓咪抓咬弄傷了嗎？來這裡讓我們細心包紮治癒您。'], ['喵喵健康針', '300,000 Gil', '主要提供給店內貓咪施打的健康針劑，如果你想讓你的貓咪朋友一起打，也一樣歡迎購買。']] },
  { title: '周邊商品・現場拍攝', items: [['與貓咪合照', '300,000 Gil', '基礎一隻貓咪，每多加一隻貓咪 +50,000 Gil。'], ['取照方式', '', '於 Discord 群內領取照片。若不希望照片公開於群內，請告知攝影的店員。']] },
]
const behaviors = ['玩樂區的貓咪比較調皮，可能會抓傷你、突然衝過來或跳到你身上，甚至趁機叼走你的點心。', '喝茶區的貓咪個性安靜許多，歡迎輕輕撫摸，但請不要用力拍打或抓弄牠們。', '點了貓咪交響樂時，附近的貓咪可能會忍不住跟著合唱，純屬牠們的社交禮儀。', '部分貓咪對小魚乾特別沒有抵抗力，可能會立刻衝過來討食，請小心手上的道具。']
const rules = ['本店為純粹的貓咪互動空間，客人不需要進行角色扮演即可入店。', '請尊重每一隻貓咪的意願，不強迫牠們與你互動或觸摸。', '貓咪就是貓咪，請勿對牠們有任何不當、色情意圖的言行。', '請勿餵食店內提供以外的食物或異物給貓咪，維護牠們的健康。', '請勿追逐、抱起或強行帶離貓咪，讓牠們保有自由活動的空間。', '歡迎自由拍照，但請隱藏角色ID。若想與貓咪合影，請購買店內的拍攝服務。直播或錄影請先向櫃台詢問。', '如有任何不當言行，店家保留請客人離場的權利，以保障貓咪與其他客人的安全。', '營業時間、地點與最新公告，請見 Discord 公告。']

function DiscordMark() { return <img src={discordIcon} alt="Discord" className="size-6" /> }

export default function Page() {
  const [activeTrait, setActiveTrait] = useState('全部'); const [selectedCat, setSelectedCat] = useState<(typeof cats)[number] | null>(null)
  const filteredCats = useMemo(() => activeTrait === '全部' ? cats : cats.filter((cat) => cat.traits.includes(activeTrait)), [activeTrait])
  return <main className="min-h-screen overflow-hidden bg-[#e8e1dc] text-[#403943]">
    <header className="relative bg-[#5a4b63] text-[#f6eee8]"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(135deg,transparent_0_48%,#8e7894_49%_50%,transparent_51%)] [background-size:34px_34px]" /><nav className="relative mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10"><a href="#top" className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-[#b9cbb9] text-[#5a4b63]"><Cat /></span><span className="font-serif text-3xl tracking-[0.15em]">貓尾草</span></a><div className="hidden items-center gap-8 text-lg md:flex"><a href="#zones">店內空間</a><a href="#cats">貓咪名簿</a><a href="#menu">消費項目</a><a href={discordUrl} target="_blank" rel="noreferrer" aria-label="加入 Discord" className="grid size-12 place-items-center rounded-lg bg-[#b9cbb9] text-[#403943] transition hover:bg-[#d2dfcc]"><DiscordMark /></a></div></nav><div id="top" className="relative mx-auto grid max-w-7xl min-h-[calc(100vh-104px)] items-center gap-12 px-6 pb-24 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:pb-32"><div className="flex flex-col justify-center"><p className="mb-6 text-lg font-bold tracking-[0.2em] text-[#c7d6c2]">WELCOME TO NEKOWEED</p><h1 className="max-w-2xl font-serif text-6xl leading-[1.08] md:text-8xl">讓故事<br /><em className="font-normal text-[#c7d6c2]">在貓尾草展開</em></h1><p className="mt-8 max-w-xl text-xl leading-9 text-[#eadfd9]">一間讓你自在親近貓咪的 RP 店。<br />在貓尾草，和一群有自己步調的貓咪相遇。</p><div className="mt-10 flex flex-wrap gap-4"><Button asChild size="lg" className="rounded-2xl bg-[#a9c3a0] px-7 text-lg text-[#403943] hover:bg-[#bfd3b7]"><a href="#cats" className="inline-flex items-center gap-2">認識店內貓咪 <ArrowUpRight className="size-5" /></a></Button><Button asChild size="lg" className="rounded-2xl border-[#a9c3a0] bg-[#a9c3a0] px-7 text-lg text-[#403943] hover:bg-[#bfd3b7]"><a href={discordUrl} target="_blank" rel="noreferrer"><DiscordMark /> <span className="sr-only">加入 Discord</span></a></Button></div></div><div className="relative min-h-[340px] lg:min-h-[440px]"><div className="absolute right-0 top-4 size-[78%] rounded-[45%_45%_12%_12%] bg-[#aa8c9f] rotate-6" /><div className="absolute bottom-0 left-2 size-[72%] rounded-[40%_40%_16%_16%] bg-[#c2b09a]" /><div className="absolute bottom-10 right-[16%] grid size-52 place-items-center rounded-[45%] bg-[#78939a] text-[#f6eee8] shadow-2xl md:size-64"><Cat className="size-36 md:size-44" strokeWidth={1.1} /><PawPrint className="absolute right-5 top-6 size-10 rotate-12 text-[#c7d6c2]" /></div><div className="absolute bottom-4 left-0 max-w-[230px] rounded-2xl bg-[#d9c5c2] px-5 py-4 text-[#5a4b63] shadow-lg"><p className="text-sm font-bold tracking-widest"></p><p className="mt-1 font-serif text-2xl">貓尾草</p></div></div></div></header>
    <section id="zones" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12 max-w-2xl"><p className="mb-3 text-lg font-bold tracking-[0.2em] text-[#816e82]">A LITTLE TOUR</p><h2 className="font-serif text-5xl md:text-6xl">店裡的四個角落</h2></div><div className="grid gap-4 md:grid-cols-4">{zones.map(([title, subtitle, text, Icon]) => { const ZoneIcon = Icon as typeof PawPrint; return <article key={title as string} className="group rounded-[1.5rem] border border-[#c8b9bc] bg-[#ddd4d0] p-6 transition hover:-translate-y-1 hover:bg-[#d3cec8]"><div className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-xl bg-[#8e7894] text-[#f8f0e8]"><ZoneIcon /></span><h3 className="font-serif text-3xl">{title as string}</h3></div><div className="mt-5 border-t border-[#b9a9ad] pt-4"><p className="text-lg leading-8 text-[#5a4b63]">{subtitle as string}</p><p className="mt-3 text-lg leading-8 text-[#625963]">{text as string}</p></div></article>})}</div></section>
    <section id="cats" className="border-y border-[#c6b6bd] bg-[#d8ccc9] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-12"><p className="mb-3 flex items-center gap-3 text-lg font-bold tracking-[0.2em] text-[#816e82]"><Cat className="size-6" /> MEET THE CATS</p><h2 className="font-serif text-5xl md:text-6xl">貓咪名簿</h2></div><div className="mb-12 rounded-[1.75rem] border border-[#bcaeb9] bg-[#c9bcc5] p-6 md:p-8"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[0.18em] text-[#6e5b70]">FILTER BY PERSONALITY</p><h3 className="mt-2 font-serif text-3xl">選一個你想遇見的性格</h3></div><p className="hidden text-lg text-[#6e5b70] md:block">點選標籤，查看有相同性格的貓咪</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{traits.map(([name, note, color]) => <button key={name} onClick={() => setActiveTrait(name)} className={`rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 ${activeTrait === name ? 'border-[#5a4b63] bg-[#5a4b63] text-[#f6eee8]' : 'border-[#b7a9b2] bg-[#e1d8d4] text-[#403943]'}`}><span className="flex items-center gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${color} text-[#403943]`}><Cat /></span><span className="text-xl font-bold">{name}</span></span><span className={`mt-3 block text-base leading-7 ${activeTrait === name ? 'text-[#eadfd9]' : 'text-[#675d66]'}`}>{note}</span></button>)}</div></div><div className="mb-6 flex items-center justify-between gap-4"><p className="text-lg text-[#665b64]">{activeTrait === '全部' ? '全部貓咪' : `符合「${activeTrait}」的貓咪`} ・ {filteredCats.length} 位</p><p className="text-right text-base font-semibold text-[#5a4b63]">點開卡片查看詳細介紹</p></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filteredCats.map((cat, i) => <button key={cat.name} onClick={() => setSelectedCat(cat)} className="group rounded-[1.5rem] border border-[#bbaab1] bg-[#e6dcda] overflow-hidden p-5 text-left transition hover:-translate-y-1 hover:shadow-xl"><div className={`relative grid aspect-square place-items-center overflow-hidden rounded-xl ${['bg-[#78939a]', 'bg-[#aa8c9f]', 'bg-[#9bae9e]'][i % 3]}`}><Cat className="size-28 text-[#f6eee8]/80 transition group-hover:scale-110" strokeWidth={1.1} /></div><h3 className="mt-5 font-serif text-3xl">{cat.name}</h3><div className="mt-3 flex flex-wrap gap-2">{[cat.role, ...cat.traits].map((tag, tagIndex) => <span key={tag} className={`rounded-full px-4 py-1.5 text-base font-semibold text-[#f6eee8] ${tagIndex === 0 ? 'bg-[#5a4b63]' : ['bg-[#8e7894]', 'bg-[#6c9290]', 'bg-[#a57d91]', 'bg-[#8c9f7a]'][tagIndex % 4]}`}>{tag}</span>)}</div><p className="mt-4 text-lg leading-8 text-[#625963]">{cat.intro}</p></button>)}</div></div></section>
    <section id="menu" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="mb-12"><p className="mb-3 text-lg font-bold tracking-[0.2em] text-[#816e82]">VISITORS&apos; MENU</p><h2 className="font-serif text-5xl md:text-6xl">消費項目</h2><p className="mt-5 text-xl text-[#625963]">需要購買任何項目請至櫃台找接待喵。</p></div><div className="flex flex-col gap-12">{menuGroups.map((group, i) => <article key={group.title} className="border-t-4 border-[#8e7894] pt-6"><div className="mb-6 flex items-center gap-4"><span className="grid size-12 place-items-center rounded-xl bg-[#5a4b63] text-[#c7d6c2]">{i === 0 ? <PawPrint /> : i === 1 ? <Sparkles /> : i === 2 ? <ShieldPlus /> : <Camera />}</span><h3 className="font-serif text-3xl">{group.title}</h3></div><div className="grid gap-5 md:grid-cols-2">{group.items.map(([name, price, text]) => <div key={name} className="rounded-2xl border border-[#c8b9bc] bg-[#ddd4d0] p-6"><div className="flex items-start justify-between gap-4"><p className="text-xl font-bold">{name}</p>{price && <p className="shrink-0 text-lg font-bold text-[#6e5b70]">{price}</p>}</div><p className="mt-3 text-lg leading-8 text-[#625963]">{text}</p></div>)}</div></article>)}</div></section>
    <section className="bg-[#78939a] px-6 py-24 text-[#f6eee8] lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="mb-3 text-lg font-bold tracking-[0.2em] text-[#c7d6c2]">PLEASE READ</p><h2 className="font-serif text-5xl md:text-6xl">貓咪可能觸發的行為</h2><div className="mt-8 flex flex-col gap-5">{behaviors.map((item) => <p key={item} className="border-l-2 border-[#c7d6c2] pl-5 text-lg leading-8 text-[#e5e1da]">{item}</p>)}</div></div><div className="rounded-[1.75rem] bg-[#5a4b63] p-8"><div className="flex items-center gap-4"><ShieldPlus className="text-[#c7d6c2]" /><h2 className="font-serif text-4xl">客人需遵守事項</h2></div><div className="mt-8 flex flex-col gap-5">{rules.map((item, i) => <p key={item} className="flex gap-4 text-lg leading-8 text-[#eadfd9]"><span className="font-mono text-[#c7d6c2]">0{i + 1}</span><span>{item}</span></p>)}</div></div></div></section>
    <footer className="bg-[#354b59] px-6 py-14 text-[#f3ece8] lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3"><Cat className="text-[#c7d6c2]" /><span className="font-serif text-3xl tracking-[0.15em]">貓尾草</span></div><p className="mt-4 text-lg text-[#e2d8d2]">給每個故事一個柔軟的落腳處。</p></div><div className="flex flex-col gap-4 text-lg text-[#e2d8d2] md:items-end"><p className="flex items-center gap-2"><Clock3 /> 營業時間、地點與最新公告請見 Discord</p><a className="grid size-12 place-items-center rounded-lg bg-[#b9cbb9] text-[#403943] transition hover:bg-[#d2dfcc]" href={discordUrl} target="_blank" rel="noreferrer" aria-label="加入 Discord"><DiscordMark /></a></div></div></footer>
    {selectedCat && <div className="fixed inset-0 z-50 grid place-items-center bg-[#403943]/80 p-4 backdrop-blur-sm" role="presentation" onClick={() => setSelectedCat(null)}><div role="dialog" aria-modal="true" aria-labelledby="cat-dialog-title" className="relative max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-[2rem] border border-[#bcaeb9] bg-[#e6dcda] shadow-2xl" onClick={(event) => event.stopPropagation()}><button aria-label="關閉介紹" onClick={() => setSelectedCat(null)} className="absolute right-4 top-4 z-10 grid size-11 place-items-center rounded-full bg-[#5a4b63] text-[#f6eee8] hover:bg-[#403943]"><X /></button><div className="grid md:grid-cols-[40%_60%]"><div className="grid min-h-72 place-items-center bg-[#78939a] text-[#f6eee8] md:min-h-[560px]"><Cat className="size-48 md:size-64" strokeWidth={1.05} /></div><div className="p-8 sm:p-10"><span className="rounded-full bg-[#5a4b63] px-4 py-2 text-base font-bold text-[#f6eee8]">{selectedCat.role}</span><h2 id="cat-dialog-title" className="mt-5 font-serif text-5xl">{selectedCat.name}</h2><div className="mt-4 flex flex-wrap gap-2">{selectedCat.traits.map((tag, i) => <span key={tag} className={`rounded-full px-3 py-1 text-sm text-[#f6eee8] ${['bg-[#8e7894]', 'bg-[#6c9290]', 'bg-[#a57d91]', 'bg-[#8c9f7a]'][i % 4]}`}>{tag}</span>)}</div><h3 className="mt-8 text-lg font-bold tracking-[0.2em] text-[#6e5b70]">貓貓介紹</h3><div className="mt-3 whitespace-pre-line text-xl leading-9 text-[#625963]">{selectedCat.detail ?? selectedCat.intro}</div>{selectedCat.likes && <><div className="mt-8 border-t border-[#c8b9bc] pt-6"><p className="text-lg font-bold tracking-widest text-[#6e5b70]">喜好</p><p className="mt-2 text-xl">{selectedCat.likes}</p></div><p className="mt-8 border-l-4 border-[#8e7894] pl-5 font-serif text-xl italic leading-9 text-[#403943]">「{selectedCat.quote}」</p></>}</div></div></div></div>}
  </main>
}
